### ISSUE TITLE
SCP-004 is missing

### ISSUE THREAD

**Issue by propensive** [scalacenter/advisoryboard#16]
This proposal (Center to coordinate SIP/SLIP process) was discussed in the first meeting, and accepted, but there's no text for it.

**Comment by adriaanm** [comment]
# Goals
  - Regain community's enthusiasm for the SIP/SLIP process.
  - Increase the community's involvement with the language and the eco-system.
  - Fair representation of community, industry and language creator & maintainers.
# Proposed approach
  - Be clear about which SIPs we would accept, provide feedback quickly (including on those SIPs we don't want to accept), make sure we keep making progress. Don't use the process to (indirectly) put PRs on hold indefinitely.
  - Minimize process overhead, clarify timing of deadlines, responsibility of various actors.
  - Should we rebrand the process? It may help to have separate technical working groups that come up with proposals and a separate process for voting on these proposals. We could integrate the latter into the Scala Center board meetings.

**Comment by SethTisue** [comment]
this was fixed a while back by c58f470fcf40d7d9e728af203bc748a3271016c8
