### ISSUE TITLE
SCP-008: Maintain scala-lang, docs.scala-lang, scala.epfl.ch websites

### ISSUE THREAD

**Issue by travissarles** [scalacenter/advisoryboard#24]
See [the proposal](https://github.com/scalacenter/advisoryboard/blob/master/proposals/008-websites.md) for details.

- [x] Fix changes to [Getting Started tutorial series](https://github.com/scala/scala-lang/pull/608)
- [x] Update Getting Started page
- [x] Look at Google Analytics to figure out which pages are getting the most hits. Use this to design a website structure.
- [x] Simplify [the docs page](http://scala-lang.org/documentation/) using the new 47 degrees template
- [x] Merge [docs.scala-lang.org](http://docs.scala-lang.org/) into scala-lang.org/documentation
- [x] Write an explanation of backends: use cases, performance, stability, etc
- [x] Update list of recommended books
- [x] Link to Scastie
- [ ] Copy templates from scala/scala-lang over to scala/scala.github.com so the style is consistent across the site
- [x] Create a new *Guides* landing page
- [x] Create a new *Reference* page
- [x] Link to "All About Scala" http://allaboutscala.com/
- [ ] Fix downloads page: Update links, fix HTML beneath IntelliJ so the links are in the right order
- [ ] Link from scala-lang.org to scala.epfl.ch and be clear about what the Scala Center does
- [ ] Link to contributing page from community page
- [x] Merge [templates designed by 47 degrees](https://github.com/scala/scala-lang/pull/606) into scala-lang
- [ ] Update the text on scala.epfl.ch with current information
- [x] Add photos of team members to scala.epfl.ch
- [x] Add a link to make changes to docs pages so it's very easy for readers to suggest quick edits
- [ ] Investigate what can be done to speed up docs site builds
- [x] Give @travissarles Admin rights to merge non-contentious pull requests 
- [ ] Develop a procedure to match contributors with issues and PRs
- [x] Find an alternative to Disqus
- [ ] [Add link to navigate from news post back to list](https://github.com/scala/scala-lang/issues/646)

**Comment by SethTisue** [comment]
that's my single-item wishlist as well :-)

**Comment by SethTisue** [comment]
closing since Travis is no longer at the Scala Center — someone could make new tickets from any remaining items
