### ISSUE TITLE
post minutes from 9 May 2016 meeting

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/advisoryboard#3]
> The minutes of the Scala Center shall be written up by the secretary after each meeting, and made available shortly afterwards in the minutes directory

yup, sure thing. might be a few days this time around because of Scala Days hecticness

**Comment by SethTisue** [comment]
@propensive @heathermiller can you add me as a committer in this repo so I can assign the ticket to myself? (and maybe be helpful in other ways in the future)

**Comment by heathermiller** [comment]
Yes, of course! You've been added :)

**Comment by SethTisue** [comment]
I've submitted a draft.

**Comment by SethTisue** [comment]
the notes are up at https://scala.epfl.ch/records.html (have been for a while)
