### ISSUE TITLE
Add a “status” field to each proposal

### ISSUE THREAD

**Issue by julienrf** [scalacenter/advisoryboard#52]
It is hard to track what’s the status of each proposal: has it been completed, or is there a work in progress, or has the proposal be withdrawn, or is it on our todo list, etc.

I propose that we add a header containing this information, at the top of each proposal:

```markdown
# Status

Completed, see [this thing](http://www.some.thing)
```

**Comment by SethTisue** [comment]
sure, I can do this.

but: would you be equally happy with a single STATUS.md file in the enclosing directory, listing the status of all the proposals?

**Comment by julienrf** [comment]
> would you be equally happy with a single STATUS.md file in the enclosing directory, listing the status of all the proposals? I'd find that easier to maintain, and I think people might find it easier to consult.

Sure! Thanks for working on this :)
