### ISSUE TITLE
The current "status" of proposals

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/advisoryboard#85]
While looking through the various proposals today I realized that there are quite a few that the "status" in the [proposals readme](https://github.com/scalacenter/advisoryboard/blob/main/proposals/README.md) hasn't been updated in quite some time. I think it'd be a good idea to do a quick review of these and to update the status in the relevant places. I'll provide a table down below of the existing proposals that "remains active" after quite some time. If need be we can discuss this during the next AB meeting, but if we're able to just take care of it this way, then no need.

| Proposal        | Current Status           | Notes  |
| ----------------|:--------------------------:|---------------|
| [002-dotty-migration-path](https://github.com/scalacenter/advisoryboard/blob/main/proposals/002-dotty-migration-path.md) | ~Remains active~ Updated to "completed" | ~There have been tools like [scala3-migrate](https://github.com/scalacenter/scala3-migrate) and a [migration guide](https://docs.scala-lang.org/scala3/guides/migration/compatibility-intro.html). Do we feel this sufficient to mark this as "completed"?~ |
| [004-sip-and-slip-coordiation](https://github.com/scalacenter/advisoryboard/blob/main/proposals/004-sip-and-slip-coordination.md) | Remains active | It says @darja is the SIP coordinator. Is this still active as intended? |
| [005-continuity-of-scala-js](https://github.com/scalacenter/advisoryboard/blob/main/proposals/005-continuity-of-scala-js.md) | ~Remains active~ Updated to "completed" | ~I'm assuming this is still correctly marked as "active".~|
| [008-websites](https://github.com/scalacenter/advisoryboard/blob/main/proposals/008-websites.md) | ~Remains active~ Updated to "completed" | ~I'm actually not 100% sure if this is the case or not?~ |
| [017-lsp-stp-wg-support](https://github.com/scalacenter/advisoryboard/blob/main/proposals/017-lsp-stp-wg-support.md) | ~Remains active~ Updated to "completed" | ~While maybe fluid in its definition, I suppose the continue support of Metals means this is correctly "active"?~ |
| [021-zinc-improvements](https://github.com/scalacenter/advisoryboard/blob/main/proposals/021-zinc-improvements.md) | Remains active | The initial timescales outline in here are far exceeded. So what would we like to do with this? |
| [022-jsr-45](https://github.com/scalacenter/advisoryboard/blob/main/proposals/022-jsr-45.md) | Remains active | From looking on GitHub, [abandoned pr in Scala 2](https://github.com/scala/scala/pull/9121) and [draft pr in Scala 3](https://github.com/lampepfl/dotty/pull/11492). |
| [024-diversity](https://github.com/scalacenter/advisoryboard/blob/main/proposals/024-diversity.md) | Remains active | I believe this is still a WIP. |
| [025-inclusive-language](https://github.com/scalacenter/advisoryboard/blob/main/proposals/025-inclusive-language.md) | Remains active | The [inclusive language guide](https://scala-lang.org/contribute/inclusive-language/) has been published, but I still see that a fair amount of repos: ~[dotty](https://github.com/lampepfl/dotty), [scalajs-bundler](https://github.com/scalacenter/scalajs-bundler), and [sbt-missinglink](https://github.com/scalacenter/sbt-missinglink) just to name a few under epfl/Scala Center that aren't actually following their own guidance with branch naming etc. Is there a reason for this?~ After the last AB meeting there needs to be a blog post published about this before being marked as completed |
| [026-solidify-getting-started-with-coursier](https://github.com/scalacenter/advisoryboard/blob/main/proposals/026-solidify-getting-started-with-coursier.md) | ~Remains active~ Update to completed | ~There are some updates in [here](https://contributors.scala-lang.org/t/simplify-the-getting-started-experience-with-coursier-roadmap/5283) and some prs to address issues, but nothing is in a stable release yet in Coursier or available via coursier/apps, so I'm assuming this is still "active".~ |

@sjrd @darjutak and/or @julienrf, I assume the three of you would know the most about the status of many of these, but anyone else that has info, please let me know and I can update accordingly.

**Comment by julienrf** [comment]
Hey @ckipp01 thank you for reporting!

Here are my inputs:

- SCP-02: the two first points are fully addressed (Scala 3 can read libraries compiled with Scala 2, and it also works the other way around, and the migration guide documents the deltas between dotc and scalac). About the third point of the proposal, I am not sure, but I would argue it is a bit vague. VirtusLab is actively contributing to the compiler, and they recently implemented a mechanism for forward-compatibility. Overall, I would lean towards saying that this proposal has been completed.
- SCP-04: still alive (though quiet for some time)
- SCP-05: it’s difficult to say what the success criteria of this proposal are. (Although I can say that it is part of our mission to make sure that Scala is accessible on other platforms than the JVM.)
- SCP-08: to be honest this proposal has completely fallen out of my radar. That being said, as a matter of facts we are helping with the maintenance and evolution of the websites (and we plan to do it even more this year). I would say that this project is completed (not in the sense that the website does not need work, but that it is clear that we are coordinating — or even leading for some parts — the evolution of the website)
- SCP-17: I think this is completed (the Scala center lead the development of the build server protocol, and the implementation of it in sbt and bloop, which is primarily used by Metals)
- SCP-21: we did not complete this proposal. Maybe we could ask the AB if we should still consider the proposal?
- SCP-22: as you noticed, our work did not cross the finish line.
- SCP-24: still in progress
- SCP-25: good catch, I agree that these branches should be renamed. Other than that, the proposal is completed, I believe.
- SCP-26: still in progress (this is taking more time than expected, but hopefully we should complete it this quarter!)

**Comment by SethTisue** [comment]
I'm okay with SCP-08 being considered complete. Website work is always ongoing of course, but the expectation that the Center is responsible (with many others, including Lightbend folks such as me, of course contributing and helping!) seems well established now.

**Comment by SethTisue** [comment]
I think SCP-005 could be considered complete on similar grounds.

**Comment by sjrd** [comment]
I agree with Julien and Seth's assessment here.

**Comment by ckipp01** [comment]
Great, thanks for all the input. I've gone ahead and updated these via #87. As for the ones that are still in progress or have been stagnant for quite some time, I'll make a small slot for them on the agenda for the next AB meeting. We can get the final clarity there on whether they are officially abandoned, worthy of renewed attention, etc.

I'll leave this open until then, do some final updates after that, and then close.

**Comment by ckipp01** [comment]
Just adding a quick note in here that we didn't have time to discuss all of these during the last meeting. The plan is to leave this open for now and update them if there are updates during this next quarter or wait until we can discuss them in the next meeting.

**Comment by julienrf** [comment]
#93 marks SCP-026 as completed.

**Comment by julienrf** [comment]
I think SCP-025 can now be marked as completed as well :) see https://www.scala-lang.org/blog-detail/2022/04/05/inclusive-language-guide.html

**Comment by SethTisue** [comment]
@ckipp01 003 is still listed as active, even though nobody's mentioned it in ages
